export const ConstantValue = {

    localStorageHero: 'name-heros',

}

export const ConstantString = {
    NameSystem: 'Marcaciones Antamina',
    EvidencePlaceHolder:
      'Registrar detalles sobre cómo llevó a cabo su inspeccion(revisión de documentos, acceso a información de base de datos, aplicativos o sistemas, entrevistas a personal de Antamina o SSEE, verificación visual directa, etc.)',
    AreSureMarking: '¿Seguro que desea registrar marcación?',
    AreSureSave: '¿Está seguro de guardar formulario?',
    AreSureClose: '¿Está seguro de cerrar el formulario?',
    AreSureDelete: '¿Está seguro de eliminar el registro?',
    AreSureDeleteVacation: '¿Está seguro de eliminar las vacaciones?',
    AreSureApprove: '¿Está seguro que desea aprobar este registro?',
    AreSureHotChange:'¿Está seguro que desea registrar un cambio en caliente?',
    Completing_data: 'Por favor, complete los datos resaltados',
    Alert: 'Alerta',
    Error: 'Error',
    OK: 'Ok',
    Confirmation: 'Confirmación',
    Required: 'Dato requerido',
    EmailInvalid: 'Correo inválido',
    MaxCharacters: 'Máximo {0} caracteres',
    MinCharacters: 'Mínimo {0} caracteres',
    FormatInvalid: 'Formato incorrecto',
    MinValid: 'Mínimo {0}',
    MaxValid: 'Máximo {0}',
    Active: 'Activo',
    Inactive: 'Inactivo',
    SuccessSave: 'Se guardo exitosamente',
    SuccessSendEmail: 'Se envio exitosamente',
    Edit: 'Editar',
    New: 'Nuevo',
    NoConnection:
      'Se encuentra sin conexión a internet, todo lo que registre no se visualizará. Terminará el registro una vez se conecte a internet.',
    NoService: 'No se encuentra el servicio',
    ErrorSendData: 'Error al enviar los datos',
    ErrorListOffline: 'Error al obtener información offline',
    FutureProcessOffline:
      'Los datos ingresados serán procesados una vez se detecte una conexión a internet',
    registerBond: 'Registro de Bonos de reemplazos (Sobretasa)',
    editBond: 'Edición de Bonos de reemplazos (Sobretasa)',
    paginationItemsPerPage: 'Elementos por página:',
    paginationFirstPage: 'Primera página',
    paginationLastPage: 'Ultima página',
    paginationNextPage: 'Página siguiente',
    paginationPreviousPage: 'Página previa',
    ErrorFind: 'No se encontraron registros',
    ArePaidOvertime: '¿Deseas que te paguen el sobretiempo?',
    userNotRosterTime:
      'El usuario no tiene un horario definido para el día de hoy.',
    AreSureCancel: '¿Está seguro de cancelar?',
    AreSureSaveRegister: '¿Está seguro de guardar registro?',
    OvertimeInvalid: 'Ingrese una cantidad menor al sobretiempo',
    CStartCEndInvalid: 'Ingrese un inicio o fin que no sea mayor al inicial',
    DescansoProgramado: 'PE_DS',
    SCHEDULE: 'SCHEDULE',
    CStartCEndIHournvalid:
      'Ingrese un hora inicio o  hora fin que no sea mayor al inicial',
    MedicalLeaveValidateHour: 'La hora fin máxima permitida es las 13:00 horas',
    AreSureAprrove: '¿Está seguro de aprobar el registro?',
    AreSureApproveVacation: '¿Está seguro de aprobar las vacaciones?',
    AreSureRejec: '¿Está seguro de rechazar el registro?',
    AreSureRejecVacation: '¿Está seguro de rechazar las vacaciones?',
    AreSureApproveOverTime: '¿Está seguro de aprobar el sobretiempo?',
    ErrorSelectRow: 'No se seleccionaron registros',
    Load: 'load',
    Next: 'next',
    Prev: 'prev',
    Search: 'search',
    AreSureRejecSTExtraordinary: '¿Está seguro de rechazar el sobretiempo extraordinario?',
    AreSureAprroves: '¿Está seguro de aprobar los registros?',
    AreSureRejecSTExtraordinarys: '¿Está seguro de rechazar los sobretiempos extraordinarios?',
  
  
  };